run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - ineffassign
    - typecheck
  disable:
    - depguard

linters-settings:
  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - badCall
      - badCond
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - flagDeref
      - nilValReturn
      - offBy1
      - sloppyReassign
      - weakCond

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: examples/
      linters:
        - errcheck
