// Command sess2tape converts a .tuisess file (produced by tuitest.SessionRecorder)
// into a VHS .tape script that can be fed to `vhs` to produce a GIF.
//
// Usage:
//
//	sess2tape [-out <file.tape>] [-width 80] [-height 24] [-fps 15] <session.tuisess>
//
// If -out is omitted the .tape is written next to the input file with the same
// base name and a .tape extension.  If the input path is "-" the session JSON
// is read from stdin and -out must be supplied (or output goes to stdout).
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SessionFormatVersion must match tuitest.SessionFormatVersion.
const SessionFormatVersion = 1

type session struct {
	Version int    `json:"version"`
	Cols    int    `json:"cols"`
	Lines   int    `json:"lines"`
	Steps   []step `json:"steps"`
}

type step struct {
	Kind   string `json:"kind"`
	Key    string `json:"key,omitempty"`
	Text   string `json:"text,omitempty"`
	Cols   int    `json:"cols,omitempty"`
	Lines  int    `json:"lines,omitempty"`
	Screen string `json:"screen,omitempty"`
}

func main() {
	var (
		out    = flag.String("out", "", "output .tape path (default: input with .tape ext; '-' for stdout)")
		width  = flag.Int("width", 0, "terminal width override (default: from session)")
		height = flag.Int("height", 0, "terminal height override (default: from session)")
		fps    = flag.Int("fps", 15, "GIF frames per second")
		delay  = flag.Int("delay", 80, "default keystroke delay in ms")
	)
	flag.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: sess2tape [flags] <session.tuisess>")
		flag.PrintDefaults()
	}
	flag.Parse()

	if flag.NArg() != 1 {
		flag.Usage()
		os.Exit(1)
	}

	inputPath := flag.Arg(0)
	var data []byte
	var err error
	if inputPath == "-" {
		data, err = os.ReadFile("/dev/stdin")
		if err != nil {
			// fallback: read stdin directly
			buf := make([]byte, 1<<20)
			n := 0
			n, err = os.Stdin.Read(buf)
			data = buf[:n]
		}
	} else {
		data, err = os.ReadFile(inputPath)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "sess2tape: read input: %v\n", err)
		os.Exit(1)
	}

	var sess session
	if err := json.Unmarshal(data, &sess); err != nil {
		fmt.Fprintf(os.Stderr, "sess2tape: parse session: %v\n", err)
		os.Exit(1)
	}
	if sess.Version != SessionFormatVersion {
		fmt.Fprintf(os.Stderr, "sess2tape: unsupported session version %d (want %d)\n", sess.Version, SessionFormatVersion)
		os.Exit(1)
	}

	cols := sess.Cols
	if *width > 0 {
		cols = *width
	}
	lines := sess.Lines
	if *height > 0 {
		lines = *height
	}

	tape := buildTape(sess, cols, lines, *fps, *delay, inputPath)

	// Determine output destination.
	if *out == "-" {
		fmt.Print(tape)
		return
	}

	outPath := *out
	if outPath == "" {
		if inputPath == "-" {
			fmt.Print(tape)
			return
		}
		base := strings.TrimSuffix(filepath.Base(inputPath), filepath.Ext(inputPath))
		outPath = filepath.Join(filepath.Dir(inputPath), base+".tape")
	}

	if err := os.WriteFile(outPath, []byte(tape), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "sess2tape: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "sess2tape: wrote %s\n", outPath)
}

// buildTape converts the session into a VHS tape script string.
func buildTape(sess session, cols, lines, fps, defaultDelay int, srcPath string) string {
	var sb strings.Builder

	srcBase := filepath.Base(srcPath)
	if srcPath == "-" {
		srcBase = "stdin"
	}
	gifName := strings.TrimSuffix(srcBase, filepath.Ext(srcBase)) + ".gif"

	sb.WriteString("# Generated by sess2tape from " + srcBase + "\n")
	sb.WriteString("# Edit settings below before running: vhs " + strings.TrimSuffix(srcBase, filepath.Ext(srcBase)) + ".tape\n\n")
	sb.WriteString("# ── VHS settings ────────────────────────────────────────────────────────────\n")
	fmt.Fprintf(&sb, "Output docs/gifs/%s\n", gifName)
	fmt.Fprintf(&sb, "Set Width %d\n", cols*8) // approx pixel width (8px per char)
	fmt.Fprintf(&sb, "Set Height %d\n", lines*16)
	fmt.Fprintf(&sb, "Set FontSize 13\n")
	fmt.Fprintf(&sb, "Set Framerate %d\n", fps)
	fmt.Fprintf(&sb, "Set PlaybackSpeed 1.0\n")
	sb.WriteString("Set Theme \"Dracula\"\n\n")
	sb.WriteString("# ── Commands ────────────────────────────────────────────────────────────────\n")
	fmt.Fprintf(&sb, "Set TypingSpeed %dms\n\n", defaultDelay/4)

	for _, s := range sess.Steps {
		switch s.Kind {
		case "key":
			sb.WriteString(vhsKey(s.Key, defaultDelay))
		case "type":
			escaped := strings.ReplaceAll(s.Text, `"`, `\"`)
			fmt.Fprintf(&sb, "Type \"%s\"\n", escaped)
			fmt.Fprintf(&sb, "Sleep %dms\n", defaultDelay)
		case "resize":
			// VHS doesn't support mid-recording resize; emit a comment.
			fmt.Fprintf(&sb, "# Resize %dx%d (not supported mid-recording by VHS)\n", s.Cols, s.Lines)
		case "screen":
			// Screen steps are assertion markers; no VHS equivalent needed.
			fmt.Fprintf(&sb, "Sleep %dms\n", defaultDelay*2)
		}
	}

	// End with a hold so the final frame is visible.
	sb.WriteString("\nSleep 2s\n")
	return sb.String()
}

// vhsKey maps tuitest key names to VHS Key commands.
func vhsKey(key string, delay int) string {
	vhsName, ok := keyMap[key]
	if !ok {
		// Unknown keys: try capitalising first letter as a best-effort.
		if len(key) > 0 {
			vhsName = strings.ToUpper(key[:1]) + key[1:]
		} else {
			return fmt.Sprintf("# unknown key %q\n", key)
		}
	}
	return fmt.Sprintf("Key %s\nSleep %dms\n", vhsName, delay)
}

// keyMap maps tuitest key names → VHS key names.
// https://github.com/charmbracelet/vhs#key
var keyMap = map[string]string{
	"up":         "Up",
	"down":       "Down",
	"left":       "Left",
	"right":      "Right",
	"enter":      "Enter",
	"tab":        "Tab",
	"shift+tab":  "Shift+Tab",
	"esc":        "Escape",
	"backspace":  "Backspace",
	"delete":     "Delete",
	"home":       "Home",
	"end":        "End",
	"pgup":       "PageUp",
	"pgdown":     "PageDown",
	"ctrl+c":     "Ctrl+C",
	"ctrl+d":     "Ctrl+D",
	"ctrl+k":     "Ctrl+K",
	"ctrl+l":     "Ctrl+L",
	"ctrl+n":     "Ctrl+N",
	"ctrl+p":     "Ctrl+P",
	"ctrl+r":     "Ctrl+R",
	"ctrl+s":     "Ctrl+S",
	"ctrl+u":     "Ctrl+U",
	"ctrl+w":     "Ctrl+W",
	"ctrl+z":     "Ctrl+Z",
	"space":      "Space",
	"f1":         "F1",
	"f2":         "F2",
	"f3":         "F3",
	"f4":         "F4",
	"f5":         "F5",
	"f10":        "F10",
}
